### ISSUE TITLE
Basic discussion about language, style etc.

### ISSUE THREAD

**Issue by LucasProgrammierStube** [DevvitIO/CMS#1]
# Hello firstly,

before we can start we need to discuss something.
This is going to be a little CMS [https://en.wikipedia.org/wiki/Content_management_system](url)

## as a second - rules:

Everything must be written down in a documentary file. (So everybody can see what we did and can literraly jump into it.)

Please be friendly and stick to the Code of Conduct on our Discord server.

## technology:

Many of us aren't very trained with HTML, CSS and JavaScript. It would be good if we stick to these, but I'm also not clearly against frameworks/libraries.

If its easier with a library or a framework we can do this. As a front-end framework we could use Bootstrap. [http://getbootstrap.com](url)

I'm not very familiar with back-end, but I have a little bit of basic experience (PHP), but we can also use NodeJS or other other like CoffeScript etc..
I will go by the majority.

How and where are we going to store the edited website and the website conent? 
Are we going to use MySQL, or such other SQL, or some other databases?
I will also go with the majority.

## design

How are we going to design it? We have to stick to the design code at the organisation's page but if you have any ideas please transmit them.

My opinion is that we need a mordern and clean design (but without Windows Metro Design) maybe a first and a design color and it should be fail safe with a explain button

## organizational part

Are we going to build some groups with expierenced and unexpierenced devs or are we going to stay in one team? 
I personally would say that we structure it like a little company with little departments wich are going to make small parts. 

**_It would be nice if you could add you personal opinion.
Happy coding <3_**

**Comment by KenavR** [comment]
One big question is, if we are going to use similar technology in every project or if we want to create diverse projects, so people can choose what they want to learn. Lanflix currently uses HTML/CSS/pure JS (ES5, ES6), NodeJS on the back end and a MongoDB datastore. Hangman is using HTML/CSS/pure JS (ES6) and I believe will end up using NodeJS since the project will need Websockets and I believe socket.io is the easiest way using them (even though it is possible with any language). **Do we want people who learn the basics of NodeJS in one project to be able to jump into another?** 

I am happy with almost anything (except CoffeeScript ;)), but since the input won't be overwhelming we should make it as simple as possible for new people.

Groups may be a great idea, but it may be an organisational nightmare, especially since we are currently a pretty small group.

**Comment by LucasProgrammierStube** [comment]
Thanks for your feedback. 

I think it is what we want because we have to build the basics and only after that we can go deeper. When everybody learns NodeJS we can make big project with everybody based on NodeJS and so everybody can contribute at a project that they like.

**Comment by Tor020** [comment]
## Technology
I suggest the same technology stack that kena is using for lanflix. Most of what i have to add on that subject is going to echo what kena has said as well as what you mentioned here. Having a learning curve that favors skill levels of low to high is the safest approach imo. That's why i rushed RAD out asap, so that those eager to do something but also too new to contribute to a more complex project had a chance to get in and do something. 

Suggested Stack: Front-End: HTML/Bootstrap  Backend: NodeJS / MongoDB

## Organization
We don't have enough numbers to organize into teams, and we also do not have the time nor necessity to try and manage teams. At least, not at the moment. It's an option for the future for sure, but for now the best way to organize for our projects is to have a leader create issues and let everyone decide which ones they want to do. A similar option is to have 2+ project leads on a project to help manage which issues are getting sorted out and adding new ones to the project board + issues on github, but that also requires those two project leads to communicate on a regular basis so that they are both aware of whats happening. The rule of thumb here that im trying to get across is that organizing into work crews isn't ideal here because it'd be less productive than letting people have freedom, but regulating the moderation of a project's path can definintely benefit from more than one person if the people leading communicate well together.


## Suggested Approach

So, I'm really not sure how a cms snaps together pages. I think that there are a lot of people in that boat too, I have no idea how to create a new file with javascript or something else and paste in code from other files. So, I'd advise keeping it barebone simple if possible. Outlining the core logic of how a CMS works would be my highest priority, but thats just me.

**Comment by LucasProgrammierStube** [comment]
Thanks, I'm totally with you. I'll edit the Issue in terms of teaming. I agree with the Stack part, but I will see if anybody has a good idea. Maybe there is someone that is really experience in this part of web development.

**Comment by AllanOcelot** [comment]
You don't want to be using Node/Mongo for the backend on this project.

Especially if you guys don't know PHP beforehand. Start with PHP, run the backend for the CMS off of MySqli and go from there. Reason? 90% of the web is made up of PHP and SQL Database's. You'll need to know them before progressing onto new tech that's moving at a much quicker speed.


Your first goal should be to come up with how to layout your database. 
How things should work in relation to each other - should be your main concern.

It might be best to start at the very very basics- make an 'options' table. Provide basics save values such as 'Website name, Website Description'. On the frontend, create a form to save and display those values to the user.

**Comment by Tor020** [comment]
Easy on the opinions there @AllanOcelot Please refer to the Code of Conduct #3 in the Discord. 

> 3. Being Heavily Opinionated is Frowned Upon

***

> You don't want to be using Node/Mongo for the backend on this project.
Especially if you guys don't know PHP beforehand. Start with PHP, run the backend for the CMS off of MySqli and go from there. Reason? 90% of the web is made up of PHP and SQL Database's. You'll need to know them before progressing onto new tech that's moving at a much quicker speed.

There is no one size fits all best way to learn for any topic, Server side programming is not an exception here. Additionally, [82% of the Internet uses PHP ](https://w3techs.com/technologies/details/pl-php/all/all). If you wanted to generalize and say the majority of the Web uses PHP that would be more acceptable. Please do not generalize and then pass off what you are saying as definitive.

>Your first goal should be to come up with how to layout your database.
How things should work in relation to each other - should be your main concern.

Why is that the main concern?

>It might be best to start at the very very basics- make an 'options' table. Provide basics save values such as 'Website name, Website Description'. On the frontend, create a form to save and display those values to the user.

While I do agree with this personally, once again, you are not explaining why.

***

When the discord first got started, there was a conversation I had with a person trying to advise someone on how to go about doing media queries. I'm going to paste it here so you can see what I'm talking about and what I said about opinons to him. 

>[3:43 PM] Benz: which you can't do with fixed media queries, because you restrict yourself/the design
[3:43 PM] Benz: and yeah, ALWAYS do mobile first
[3:43 PM] Benz: if you don#t do mobile first, you will run into problems
[3:44 PM] Benz: or ugly code
[3:44 PM] Tor: Benz try to be more opinion agnostic about that
[3:45 PM] Tor: do not say always,  and never say never. Strongly suggest your opinion and provide compelling evidence that correlates but do not say absolutes
[3:45 PM] Tor: ty
[3:45 PM] Benz: well, it's a best practice
[3:45 PM] Tor: "Most people consider it a best practice"
[3:45 PM] Tor: is what is better to say
[3:46 PM] Benz: that's redundand to say
[3:46 PM] Tor: You give people the information and let them choose you do not make the decision for them
[3:46 PM] Benz: if most people wouldn't say that it wouldn't be a "best practice"
[3:46 PM] Benz: best practices are born by a large amount of people adopting certain things
[3:46 PM] Benz: so by saying something is a "best practicse" you already imply "most people"
[3:46 PM] Tor: you're looking at it the wrong way.
[3:47 PM] Tor: It's about from the perspective of the individual
[3:48 PM] Benz: ...... what?
[3:48 PM] Tor: there will always be people who don't want to do something, and don't do it. Saying "it's a best practice" is stating it like saying the number 5 + the number 5 will be 10
[3:49 PM] Tor: If someone is new to development, and haven't learned to understand it as you say in a way that limits redundancy, you're not doing them any favors by saying A. is true
[3:49 PM] Tor: emphasis of the redundancy is fine, it's like commenting code that you know works but for the next person
[3:50 PM] Tor: Thanks

***

I would appreciate it if in the future you would take this style of approach towards sharing your opinion in the future.

Thanks

**Comment by KenavR** [comment]
I saw the PHP label in issue #5, are we going with PHP as backend language? Also, did you decide on a database system? I am fine with PHP and since my last experience with it was almost 10 years ago I may also contribute a little bit more to the code. It has some advantages, but also some drawbacks in the context of this community. I am going to add some comments regarding the project's architecture.

**Comment by LucasProgrammierStube** [comment]
PHP would do the login and verification part because that is a solid way without any add-in or add-ons.
If there are any other easy ways to do so please tell me.
