### ISSUE TITLE
We need a user database

### ISSUE THREAD

**Issue by LucasProgrammierStube** [DevvitIO/CMS#5]
We need a user database that stores the user data (login credentials) for the login.

-------

1. random user #1 creates a profile
2. database stores his credentials

**Comment by KenavR** [comment]
Are you planning on it being a website where people can register and then host there site there (wordpress.com, wix, medium,...) or a CMS that people can install on there own server and host their site on their own infrastructure? 

If the later, I am not sure why we need "3. creates a folder associated with random user #1", since there is only one site which every "admin" works on. 

Additional we should think about how to store the content, either in a directory structure (as you suggested), in the database or mixed. Another decision would be if there is a separate admin console (multiple interfaces), where content is edited or if an admin just has more features on the view every user sees (single interface).

**Comment by LucasProgrammierStube** [comment]
@KenavR I didnt thought shout it but this is a pretty damn good idea. It would be easier and we are not responsible for their data and their bandwidth etc.
